### ISSUE TITLE
I have a question , please help!!!

### ISSUE THREAD

**Issue by sunyinhui** [kevinlin311tw/caffe-cvprw15#1]
![kevinnet demo error](https://cloud.githubusercontent.com/assets/6357309/12031520/d5209394-ae47-11e5-9f4e-80ca679bd4af.png)

**Comment by willard-yuan** [comment]
@sunyinhui , You should make sure your GPU works first.

**Comment by sunyinhui** [comment]
This is my Makefile.config 

# cuDNN acceleration switch (uncomment to build with cuDNN).

# USE_CUDNN := 1

# CPU-only switch (uncomment to build without GPU support).

# CPU_ONLY := 1

How can i make sure the GPU is working ???  Thanks !!!

**Comment by kevinlin311tw** [comment]
Hi @sunyinhui 

1) According to the error message, caffe cannot find the network model. Please make sure you have downloaded the network model. You can download the model by running the command: ./download_model.sh

2) please do not include Chinese character such as 下載 in the path.

**Comment by sunyinhui** [comment]
@kevinlin311tw   Thanks !!
like is :  is it works??? 
![demo caffe](https://cloud.githubusercontent.com/assets/6357309/12046006/e0cffe8a-aee9-11e5-9724-0a0ce1cd11be.png)

**Comment by sunyinhui** [comment]
demo
    '/examples/cvprw15-cifar10/imgs/horse2.jpg'
    '/examples/cvprw15-cifar10/imgs/horse1.jpg'
    '/examples/cvprw15-cifar10/imgs/car2.jpg'
    '/examples/cvprw15-cifar10/imgs/bird2.jpg'
    '/examples/cvprw15-cifar10/imgs/bus1.jpg'
    '/examples/cvprw15-cifar10/imgs/car1.jpg'
    '/examples/cvprw15-cifar10/imgs/air1.jpg'
    '/examples/cvprw15-cifar10/imgs/bird1.jpg'
    '/examples/cvprw15-cifar10/imgs/air2.jpg'
    '/examples/cvprw15-cifar10/imgs/bus2.jpg'
    '/examples/cvprw15-cifar10/imgs/deer1.jpg'
    '/examples/cvprw15-cifar10/imgs/deer2.jpg'

Warning: Assuming batches of 10 images rest will be filled with zeros 

> In matcaffe_batch_KevinNet_CIFAR10_48 at 35
>   In demo at 24 
> Done with init
> Using CPU Mode
> Done with set_mode

num_batches =

```
 2
```

Starting parallel pool (parpool) using the 'local' profile ... connected to 2 workers.

 Preparing /examples/cvprw15-cifar10/imgs/air1.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/car1.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/bus1.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/bird2.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/car2.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/horse1.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/horse2.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/air2.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/bird1.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/bus2.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 
> Elapsed time is 23.612873 seconds.
> Batch 1 out of 2 50.00% Complete ETA 23.63 seconds
> Elapsed time is 1.215083 seconds.
> Elapsed time is 24.846506 seconds.

 Preparing /examples/cvprw15-cifar10/imgs/deer2.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/deer1.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 
> Elapsed time is 0.065138 seconds.
> Batch 2 out of 2 100.00% Complete ETA 0.00 seconds
> Elapsed time is 1.160640 seconds.
> Elapsed time is 1.226573 seconds.
> Elapsed time is 26.073577 seconds.
>     '/examples/cvprw15-cifar10/imgs/horse2.jpg'
>     '/examples/cvprw15-cifar10/imgs/horse1.jpg'
>     '/examples/cvprw15-cifar10/imgs/car2.jpg'
>     '/examples/cvprw15-cifar10/imgs/bird2.jpg'
>     '/examples/cvprw15-cifar10/imgs/bus1.jpg'
>     '/examples/cvprw15-cifar10/imgs/car1.jpg'
>     '/examples/cvprw15-cifar10/imgs/air1.jpg'
>     '/examples/cvprw15-cifar10/imgs/bird1.jpg'
>     '/examples/cvprw15-cifar10/imgs/air2.jpg'
>     '/examples/cvprw15-cifar10/imgs/bus2.jpg'
>     '/examples/cvprw15-cifar10/imgs/deer1.jpg'
>     '/examples/cvprw15-cifar10/imgs/deer2.jpg'

Warning: Assuming batches of 10 images rest will be filled with zeros 

> In matcaffe_batch_KevinNet_CIFAR10_4096 at 36
>   In demo at 43 
> Done with init
> Using CPU Mode
> Done with set_mode

num_batches =

```
 2
```

 Preparing /examples/cvprw15-cifar10/imgs/air1.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/car1.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/bus1.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/bird2.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/car2.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/horse1.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/horse2.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/bus2.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/air2.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/bird1.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 
> Elapsed time is 0.077501 seconds.
> Batch 1 out of 2 50.00% Complete ETA 0.08 seconds
> Elapsed time is 1.179028 seconds.
> Elapsed time is 1.257639 seconds.

 Preparing /examples/cvprw15-cifar10/imgs/deer2.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 

 Preparing /examples/cvprw15-cifar10/imgs/deer1.jpg
Warning: Problems with file

> In prepare_batch>(parfor body) at 39
>   In parallel_function>make_general_channel/channel_general at 914
>   In remoteParallelFunction at 38 
> Elapsed time is 0.054032 seconds.
> Batch 2 out of 2 100.00% Complete ETA 0.00 seconds
> Elapsed time is 1.168558 seconds.
> Elapsed time is 1.222938 seconds.
> Elapsed time is 2.480800 seconds.
> IdleTimeout has been reached.
> Parallel pool using the 'local' profile is shutting down.
>

**Comment by kevinlin311tw** [comment]
@sunyinhui
Check out the matrix "binary_codes", and you should find the 48-bit binary codes for each image.

**Comment by sunyinhui** [comment]
@kevinlin311tw   yeah！　I get it, but  it's all 1, not find zero! 
Is the imageData too little or others reasons???   Thanks !!!

**Comment by kevinlin311tw** [comment]
@sunyinhui 

1) The outputs should have 0s and 1s. You didn't get the correct results.  

2) According to your error message, "Warning: Problems with file," this indicates caffe didn't get the input data. (Should be okay if default, very strange here!!!!!)  Please check again your input data and the data path in "img_list.txt"

**Comment by sunyinhui** [comment]
I have a try, it's work!  It's my carelessness!!! (I am a newbie ) 
Thank you for your help and sharing!
Thank you very much!!!

**Comment by sunyinhui** [comment]
@kevinlin311tw  Thank you!  your work is  awesome!!!
