### ISSUE TITLE
error when running train_48.sh

### ISSUE THREAD

**Issue by brisker** [kevinlin311tw/caffe-cvprw15#11]
0804 21:10:01.285056 24109 solver.cpp:58] Creating training net from train_net file: train_CIFAR10_48.prototxt
E0804 21:10:01.285750 24109 upgrade_proto.cpp:594] Attempting to upgrade input file specified using deprecated V0LayerParameter: train_CIFAR10_48.prototxt
E0804 21:10:01.286242 24109 upgrade_proto.cpp:395] Unknown parameter det_fg_threshold for layer type data
E0804 21:10:01.286269 24109 upgrade_proto.cpp:405] Unknown parameter det_bg_threshold for layer type data
E0804 21:10:01.286285 24109 upgrade_proto.cpp:415] Unknown parameter det_fg_fraction for layer type data
E0804 21:10:01.286298 24109 upgrade_proto.cpp:425] Unknown parameter det_context_pad for layer type data
E0804 21:10:01.286310 24109 upgrade_proto.cpp:435] Unknown parameter det_crop_mode for layer type data
E0804 21:10:01.286380 24109 upgrade_proto.cpp:598] Warning: had one or more problems upgrading V0NetParameter to NetParameter (see above); continuing anyway.
E0804 21:10:01.286397 24109 upgrade_proto.cpp:604] Note that future Caffe releases will not support V0NetParameter; use ./build/tools/upgrade_net_proto_text for prototxt and ./build/tools/upgrade_net_proto_binary for model weights upgrade this and any other net protos to the new format.

.........................
 I0804 21:04:28.309278 24038 data_layer.cpp:45] Opening leveldb cifar10_train_leveldb
And the code just stop here, no training!!!

**Comment by kevinlin311tw** [comment]
@brisker Did you build the leveldb file? I think the problem is that caffe cannot find this leveldb.

**Comment by brisker** [comment]
@kevinlin311tw   I have built it:
![image](https://cloud.githubusercontent.com/assets/13804492/17656011/f7340646-62e7-11e6-8ee1-4cf85fd801fb.png)
Why can't caffe find this?

**Comment by brisker** [comment]
@kevinlin311tw 
 the train-file-list reads like this: but in the "/dataset" folder there is no batch1, batch2..etc folder .So I need to download them by myself? But the prepare_train.sh downloaded the binary version, do I need to download the source images of cifar10?
![image](https://cloud.githubusercontent.com/assets/13804492/17657250/2b11e044-62f4-11e6-8ac2-cb5bd28ae26f.png)

**Comment by kevinlin311tw** [comment]
Did u run this?

$ ./prepare_eval.sh

**Comment by brisker** [comment]
@kevinlin311tw 
yes, I forgot it! It works, thanks
