### ISSUE TITLE
Demo.m Error !!

### ISSUE THREAD

**Issue by ghost** [kevinlin311tw/caffe-cvprw15#14]
Please help with the error. Thank You. :) 

```
>> startup
caffe-cvprw15 startup
>> demo
    '/examples/cvprw15-cifar10/imgs/horse2.jpg'
    '/examples/cvprw15-cifar10/imgs/horse1.jpg'
    '/examples/cvprw15-cifar10/imgs/car2.jpg'
    '/examples/cvprw15-cifar10/imgs/bird2.jpg'
    '/examples/cvprw15-cifar10/imgs/bus1.jpg'
    '/examples/cvprw15-cifar10/imgs/car1.jpg'
    '/examples/cvprw15-cifar10/imgs/air1.jpg'
    '/examples/cvprw15-cifar10/imgs/bird1.jpg'
    '/examples/cvprw15-cifar10/imgs/air2.jpg'
    '/examples/cvprw15-cifar10/imgs/bus2.jpg'
    '/examples/cvprw15-cifar10/imgs/deer1.jpg'
    '/examples/cvprw15-cifar10/imgs/deer2.jpg'

Warning: Assuming batches of 10 images rest will be filled with zeros 
> In matcaffe_batch_feat at 35
  In demo at 29 
Undefined function 'caffe' for input arguments of type 'char'.

Error in matcaffe_init_feat (line 27)
  caffe('init', model_def_file, model_file)

Error in matcaffe_batch_feat (line 39)
matcaffe_init_feat(use_gpu, model_def_file, model_file);

Error in demo (line 29)
[feat_test , list_im] = matcaffe_batch_feat(test_file_list, use_gpu, feat_len, model_def_file,
model_file);
```

**Comment by kevinlin311tw** [comment]
This doesn't look like a bug. Make sure you have correctly compiled matlab wrapper according to http://caffe.berkeleyvision.org/tutorial/interfaces.html#matlab
and you have compiled mex file caffe_.mexa64 (extension may vary on your platform)
in caffe/matlab/+caffe/private/

**Comment by ghost** [comment]
I have tried installing the _**caffe-cvprw15**_  in two ways, and in both ways, strictly following the http://caffe.berkeleyvision.org/tutorial/interfaces.html#matlab steps and satisfying all the prerequisites.

# **_1st way:_**

git clone --recursive https://github.com/kevinlin311tw/caffe-cvprw15
modifying Makefile.config
make all -j4

but then it threw the following error:

> g++ .build_release/tools/extract_features.o .build_release/lib/libcaffe.a -o .build_release/tools/extract_features.bin -fPIC -DNDEBUG -O2 -DCPU_ONLY -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I/usr/include/hdf5/serial -I.build_release/src -I./src -I./include -Wall -Wno-sign-compare -L/usr/lib -L/usr/local/lib -L/usr/lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lpthread -lglog -lgflags -lprotobuf -lleveldb -lsnappy -llmdb -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lcblas -latlas
> ..build_release/lib/libcaffe.a(io.o): In function `caffe::ReadImageToDatum(std::__cxx11::basic_string<char, std::char_traits<char>, std::build_releaseallocator<char/> >lib const&, /int, libcaffe.aint, (int, io.obool, )caffe::Datum*)':
> io.cpp:(.text+:0x5d7): undefined reference to`cv::imread(cv::String  const&, int)'
> In function `caffe::ReadImageToDatum(std::__cxx11::basic_string<collect2: error: ld returned 1 exit status
> char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, bool, caffe::Datum*)':
> io.cpp:(.text+0x5d7): undefined reference to`cv::imread(cv::String const&, int)'
> collect2: error: ld returned 1 exit status
> Makefile:492: recipe for target '.build_release/tools/upgrade_net_proto_text.bin' failed
> make: **\* [.build_release/tools/upgrade_net_proto_text.bin] Error 1
> make: **\* Waiting for unfinished jobs....
> Makefile:492: recipe for target '.build_release/tools/compute_image_mean.bin' failed
> make: **\* [.build_release/tools/compute_image_mean.bin] Error 1
> .build_release/lib/libcaffe.a(io.o): In function `caffe::ReadImageToDatum(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, bool, caffe::Datum*)':
> io.cpp:(.text+0x5d7): undefined reference to`cv::imread(cv::String const&, int)'
> .build_release/lib/libcaffe.a(window_data_layer.o): In function `caffe::WindowDataLayer<float>::InternalThreadEntry()':
> window_data_layer.cpp:(.text._ZN5caffe15WindowDataLayerIfE19InternalThreadEntryEv[_ZN5caffe15WindowDataLayerIfE19InternalThreadEntryEv]+0x3f6): undefined reference to`cv::imread(cv::String const&, int)'
> .build_release/lib/libcaffe.a(window_data_layer.o): In function `caffe::WindowDataLayer<double>::InternalThreadEntry()':
> window_data_layer.cpp:(.text._ZN5caffe15WindowDataLayerIdE19InternalThreadEntryEv[_ZN5caffe15WindowDataLayerIdE19InternalThreadEntryEv]+0x403): undefined reference to`cv::imread(cv::String const&, int)'
> collect2: error: ld returned 1 exit status
> Makefile:492: recipe for target '.build_release/tools/caffe.bin' failed
> make: **\* [.build_release/tools/caffe.bin] Error 1
> .build_release/lib/libcaffe.a(io.o): In function `caffe::ReadImageToDatum(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, bool, caffe::Datum*)':
> io.cpp:(.text+0x5d7): undefined reference to`cv::imread(cv::String const&, int)'
> .build_release/lib/libcaffe.a(window_data_layer.o): In function `caffe::WindowDataLayer<float>::InternalThreadEntry()':
> window_data_layer.cpp:(.text._ZN5caffe15WindowDataLayerIfE19InternalThreadEntryEv[_ZN5caffe15WindowDataLayerIfE19InternalThreadEntryEv]+0x3f6): undefined reference to`cv::imread(cv::String const&, int)'
> .build_release/lib/libcaffe.a(window_data_layer.o): In function `caffe::WindowDataLayer<double>::InternalThreadEntry()':
> window_data_layer.cpp:(.text._ZN5caffe15WindowDataLayerIdE19InternalThreadEntryEv[_ZN5caffe15WindowDataLayerIdE19InternalThreadEntryEv]+0x403): undefined reference to`cv::imread(cv::String const&, int)'
> collect2: error: ld returned 1 exit status
> Makefile:492: recipe for target '.build_release/tools/extract_features.bin' failed
> make: **\* [.build_release/tools/extract_features.bin] Error 1

Prior to this I had many errors, but some how surpassed them tweaking something or the other, but was unable to go further than this.

Therefore, I tried the 2nd way,

# **_2nd way:_**

`git clone git://github.com/BVLC/caffe.git

cd caffe

sudo cp Makefile.config.example Makefile.config

sudo gedit Makefile.config`

Made changes in config file similar to done previously like, the following -

```
CPU_ONLY := 1
PYTHON_INCLUDE := /usr/include/python2.7 /usr/lib/python2.7/dist-packages/numpy/core/include
WITH_PYTHON_LAYER := 1
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/include/hdf5/serial
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/hdf5/serial

and matlab directory ofcourse.
```

then the following commands,

```
make all -j4
make test -j4
make matcaffe -j4
```

all the above ran successfully, unlike the 1st way.

the opened matlab, with those errors to avoid the _libstdc++.so.6:version 'GLIBCXX_3.4.15'_ errors.
and also checked the same by running,

`!ldd ./matlab/+caffe/private/caffe_.mexa64`

in matlab.

Further, copying the necessary files from your caffe-cvprw15 package (like demo.m, startup.m, the caffe folder, the examples folder, etc).

> > > startup
> > > caffe-cvprw15 startup
> > > demo
> > >     '/examples/cvprw15-cifar10/imgs/horse2.jpg'
> > >     '/examples/cvprw15-cifar10/imgs/horse1.jpg'
> > >     '/examples/cvprw15-cifar10/imgs/car2.jpg'
> > >     '/examples/cvprw15-cifar10/imgs/bird2.jpg'
> > >     '/examples/cvprw15-cifar10/imgs/bus1.jpg'
> > >     '/examples/cvprw15-cifar10/imgs/car1.jpg'
> > >     '/examples/cvprw15-cifar10/imgs/air1.jpg'
> > >     '/examples/cvprw15-cifar10/imgs/bird1.jpg'
> > >     '/examples/cvprw15-cifar10/imgs/air2.jpg'
> > >     '/examples/cvprw15-cifar10/imgs/bus2.jpg'
> > >     '/examples/cvprw15-cifar10/imgs/deer1.jpg'
> > >     '/examples/cvprw15-cifar10/imgs/deer2.jpg'
> 
> Warning: Assuming batches of 10 images rest will be filled with zeros 
> 
> > In matcaffe_batch_feat at 35
> >   In demo at 29 
> > Undefined function 'caffe' for input arguments of type 'char'.
> 
> Error in matcaffe_init_feat (line 27)
>   caffe('init', model_def_file, model_file)
> 
> Error in matcaffe_batch_feat (line 39)
> matcaffe_init_feat(use_gpu, model_def_file, model_file);
> 
> Error in demo (line 29)
> [feat_test , list_im] = matcaffe_batch_feat(test_file_list, use_gpu, feat_len, model_def_file,
> model_file);

as far as i understand matlab, 

> Undefined function 'caffe' for input arguments of type 'char'.

means that matlab isn't able to find the function _caffe_ in the following location,

> Error in matcaffe_init_feat (line 27)
>   caffe('init', model_def_file, model_file)

However, I don't understand even after adding the complete directory of caffe-cvprw15 via startup.m,
why would it give such an error.

I would like you to please kindly help me through this, I have tried stating each and every step I followed, for your convenience and understanding. I am ready to make a clean installation of the same or any other tweaks you suggest.

Thank You once again Kevin.

**Comment by kevinlin311tw** [comment]
Since you use the latest caffe, you should update the matlab interface to the latest version.

**Comment by kevinlin311tw** [comment]
That is, you may check [this](https://github.com/BVLC/caffe/blob/master/matlab/demo/classification_demo.m) and update the matlab interface in `matcaffe_init_feat.m` and `matcaffe_batch_feat.m` accordingly.

**Comment by ghost** [comment]
@kevinlin311tw  could not clearly understand what you meant by,

> update the matlab interface **in** matcaffe_init_feat.m and matcaffe_batch_feat.m accordingly

as matcaffe_init_feat.m and matcaffe_batch_feat.m do no exist in the newer version, infact the caffe folder _~/caffe-cvprw15/matlab/caffe_ itself doesn't exist, seems to be replaced by _[~/caffe/matlab/+caffe](https://github.com/BVLC/caffe/tree/master/matlab/%2Bcaffe)_ i guess.

**Comment by kevinlin311tw** [comment]
These two files are written by us. You can not find them in the official caffe.

The interfaces are different. For example, the old caffe uses `caffe('init', model_def_file, model_file);` to initialize the network. However, the latest caffe uses `net = caffe.Net(net_model, net_weights, phase);` to initialize network. 

You may modify the matlab code by yourself since you are not using the caffe we provided. I am now busy with my midterm. I can not help you write code.

**Comment by jinian2614** [comment]
I compiled your caffe, but how can I realize image retrieval?

**Comment by Fredkids** [comment]
I have encountered the same problem with you, how do you solve the problem?

**Comment by vra** [comment]
Hi guys,
I encountered the same problem when compile this repo. the compile failed with error message: " undefined reference tocv::imread(cv::String const&, int)". This is because this repo use an old version of caffe, which cannot find OpenCV correctly. I update Makefile and Makefile.config in my fork <https://github.com/vra/caffe-cvprw15> so that the compiler will find OpenCV automatically. Hope this helps.
