### ISSUE TITLE
could someone help me with my issues

### ISSUE THREAD

**Issue by sjean** [kevinlin311tw/caffe-cvprw15#16]
#when i execute make all -j16, this is error codes
i tried everything i can do, still can not figure it out.
thanks very much if anyone can help me.

`In file included from ./include/caffe/loss_layers.hpp:11:0,
                 from src/caffe/layers/contrastive_loss_layer.cpp:5:
./include/caffe/neuron_layers.hpp:383:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_;
   ^
./include/caffe/neuron_layers.hpp:384:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t top_desc_;
   ^
./include/caffe/neuron_layers.hpp:467:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_;
   ^
./include/caffe/neuron_layers.hpp:468:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t top_desc_;
   ^
./include/caffe/neuron_layers.hpp:553:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_;
   ^
./include/caffe/neuron_layers.hpp:554:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t top_desc_;
   ^
Makefile:501: recipe for target '.build_release/src/caffe/layers/contrastive_loss_layer.o' failed
make: *** [.build_release/src/caffe/layers/contrastive_loss_layer.o] Error 1
make: *** Waiting for unfinished jobs....

In file included from ./include/caffe/loss_layers.hpp:11:0,
                 from ./include/caffe/common_layers.hpp:12,
                 from ./include/caffe/vision_layers.hpp:10,
                 from src/caffe/layers/relu_layer.cpp:5:
./include/caffe/neuron_layers.hpp:383:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_;
   ^
./include/caffe/neuron_layers.hpp:384:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t top_desc_;
   ^
./include/caffe/neuron_layers.hpp:467:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_;
   ^
./include/caffe/neuron_layers.hpp:468:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t top_desc_;
   ^
./include/caffe/neuron_layers.hpp:553:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_;
   ^
./include/caffe/neuron_layers.hpp:554:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t top_desc_;
   ^
In file included from ./include/caffe/vision_layers.hpp:10:0,
                 from src/caffe/layers/relu_layer.cpp:5:
./include/caffe/common_layers.hpp:410:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_;
   ^
./include/caffe/common_layers.hpp:411:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t top_desc_;
   ^
In file included from src/caffe/layers/relu_layer.cpp:5:0:
./include/caffe/vision_layers.hpp:148:10: error: ‘cudnnTensor4dDescriptor_t’ was not declared in this scope
   vector<cudnnTensor4dDescriptor_t> bottom_descs_, top_descs_;
          ^
./include/caffe/vision_layers.hpp:148:35: error: template argument 1 is invalid
   vector<cudnnTensor4dDescriptor_t> bottom_descs_, top_descs_;
                                   ^
./include/caffe/vision_layers.hpp:148:35: error: template argument 2 is invalid
./include/caffe/vision_layers.hpp:149:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t    bias_desc_;
   ^
./include/caffe/vision_layers.hpp:347:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_, top_desc_;
   ^
Makefile:501: recipe for target '.build_release/src/caffe/layers/relu_layer.o' failed
make: *** [.build_release/src/caffe/layers/relu_layer.o] Error 1

In file included from ./include/caffe/loss_layers.hpp:11:0,
                 from ./include/caffe/common_layers.hpp:12,
                 from ./include/caffe/vision_layers.hpp:10,
                 from src/caffe/layers/euclidean_loss_layer.cpp:6:
./include/caffe/neuron_layers.hpp:383:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_;
   ^
./include/caffe/neuron_layers.hpp:384:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t top_desc_;
   ^
./include/caffe/neuron_layers.hpp:467:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_;
   ^
./include/caffe/neuron_layers.hpp:468:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t top_desc_;
   ^
./include/caffe/neuron_layers.hpp:553:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_;
   ^
./include/caffe/neuron_layers.hpp:554:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t top_desc_;
   ^
In file included from ./include/caffe/vision_layers.hpp:10:0,
                 from src/caffe/layers/euclidean_loss_layer.cpp:6:
./include/caffe/common_layers.hpp:410:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_;
   ^
./include/caffe/common_layers.hpp:411:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t top_desc_;
   ^
In file included from src/caffe/layers/euclidean_loss_layer.cpp:6:0:
./include/caffe/vision_layers.hpp:148:10: error: ‘cudnnTensor4dDescriptor_t’ was not declared in this scope
   vector<cudnnTensor4dDescriptor_t> bottom_descs_, top_descs_;
          ^
./include/caffe/vision_layers.hpp:148:35: error: template argument 1 is invalid
   vector<cudnnTensor4dDescriptor_t> bottom_descs_, top_descs_;
                                   ^
./include/caffe/vision_layers.hpp:148:35: error: template argument 2 is invalid
./include/caffe/vision_layers.hpp:149:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t    bias_desc_;
   ^
./include/caffe/vision_layers.hpp:347:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_, top_desc_;
   ^
Makefile:501: recipe for target '.build_release/src/caffe/layers/euclidean_loss_layer.o' failed
make: *** [.build_release/src/caffe/layers/euclidean_loss_layer.o] Error 1

In file included from ./include/caffe/loss_layers.hpp:11:0,
                 from ./include/caffe/common_layers.hpp:12,
                 from ./include/caffe/vision_layers.hpp:10,
                 from src/caffe/layers/tanh_layer.cpp:8:
./include/caffe/neuron_layers.hpp:383:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_;
   ^
./include/caffe/neuron_layers.hpp:384:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t top_desc_;
   ^
./include/caffe/neuron_layers.hpp:467:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_;
   ^
./include/caffe/neuron_layers.hpp:468:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t top_desc_;
   ^
./include/caffe/neuron_layers.hpp:553:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_;
   ^
./include/caffe/neuron_layers.hpp:554:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t top_desc_;
   ^
In file included from ./include/caffe/vision_layers.hpp:10:0,
                 from src/caffe/layers/tanh_layer.cpp:8:
./include/caffe/common_layers.hpp:410:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_;
   ^
./include/caffe/common_layers.hpp:411:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t top_desc_;
   ^
In file included from src/caffe/layers/tanh_layer.cpp:8:0:
./include/caffe/vision_layers.hpp:148:10: error: ‘cudnnTensor4dDescriptor_t’ was not declared in this scope
   vector<cudnnTensor4dDescriptor_t> bottom_descs_, top_descs_;
          ^
./include/caffe/vision_layers.hpp:148:35: error: template argument 1 is invalid
   vector<cudnnTensor4dDescriptor_t> bottom_descs_, top_descs_;
                                   ^
./include/caffe/vision_layers.hpp:148:35: error: template argument 2 is invalid
./include/caffe/vision_layers.hpp:149:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t    bias_desc_;
   ^
./include/caffe/vision_layers.hpp:347:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_, top_desc_;
   ^
Makefile:501: recipe for target '.build_release/src/caffe/layers/tanh_layer.o' failed
make: *** [.build_release/src/caffe/layers/tanh_layer.o] Error 1
`

**Comment by iWeisskohl** [comment]
you don't need to use cudnn here,cause the packeg codes run without cudnn,make sure you have #the cudnn function in Makefile.config
