### ISSUE TITLE
How can i train my datas? ths 

### ISSUE THREAD

**Issue by sunyinhui** [kevinlin311tw/caffe-cvprw15#2]
when i train my datas i face the problem. 
![qq 20160117165507](https://cloud.githubusercontent.com/assets/6357309/12376722/507683b4-bd3e-11e5-8ba9-64d545f476c8.png)

**Comment by sunyinhui** [comment]
Lenovo caffe-cvprw15-master-image-retrieval-test # sh examples/cvprw15-cifar10/train_48.sh 
examples/cvprw15-cifar10/train_48.sh: 1: examples/cvprw15-cifar10/train_48.sh: ../../build/tools/caffe: not found

**Comment by kevinlin311tw** [comment]
Remake caffe with sudo:

sudo make all
sudo make test
sudo make runtest
sudo make matcaffe

**Comment by kevinlin311tw** [comment]
Go to the folder `/examples/cvprw15-cifar10`, and run the training script:
$ cd /examples/cvprw15-cifar10
$ ./train_48.sh

**Comment by sunyinhui** [comment]
It works!
I konw the problem of GPU(GT 635M), I get the problem. Can i use the CPU only ? ths! I try again
![caffenvidia](https://cloud.githubusercontent.com/assets/6357309/12381545/f58235f0-bdc6-11e5-9fc4-320e8aa13c6e.png)

**Comment by kevinlin311tw** [comment]
Hi @sunyinhui 
Do you mean you want to train with CPU? Two things you need to do.

1.Modify the solver 
     $ vi solver_CIFAR10_48.prototxt
    <<<<<<<<<<<<<<<<<<<< before
    14 snapshot_prefix: "KevinNet_CIFAR10_48"
    -------------------------------------------
    14 snapshot_prefix: "KevinNet_CIFAR10_48"
    15 solver_mode: CPU
    >>>>>>>>>>>>>>>>>>>>> after

2.Modify the training script
    $ vi train_48.sh
    <<<<<<<<<<<<<<<<<<<< before
    ../../build/tools/caffe .....  -gpu 0 2>&1 | tee log.txt
    -------------------------------------------
    ../../build/tools/caffe ..... 2>&1 | tee log.txt
    >>>>>>>>>>>>>>>>>>>>> after

**Comment by sunyinhui** [comment]
It works. Thank you for your enthusiastic
