### ISSUE TITLE
Undefined function or variable 'matcaffe_batch_feat'.

### ISSUE THREAD

**Issue by lxtGH** [kevinlin311tw/caffe-cvprw15#21]
**I run the scripts and get the caffemodel ,KevinNet_CIFAR10_48.caffemodel**
Undefined function or variable 'matcaffe_batch_feat'.

Error in demo (line 29)
[feat_test , list_im] = matcaffe_batch_feat(test_file_list, use_gpu, feat_len,
model_def_file, model_file);

**Comment by kevinlin311tw** [comment]
How about run`addpath(genpath(pwd));`, and then run`demo.m`?
