### ISSUE TITLE
How to extract the features from fc7 layer?

### ISSUE THREAD

**Issue by sunyinhui** [kevinlin311tw/caffe-cvprw15#3]

**Comment by sunyinhui** [comment]
is the datas of  fc7 layer save in feat4096.mat???  ths

**Comment by kevinlin311tw** [comment]
You may find answer such as [this](https://github.com/kevinlin311tw/caffe-cvprw15/blob/master/demo.m#L36) and [this](https://github.com/kevinlin311tw/caffe-cvprw15/blob/master/demo.m#L59).

**Comment by sunyinhui** [comment]
Thanks a lot !!!

**Comment by sunyinhui** [comment]
I am sorry,  Kevinlin!!!  ^-^

**Comment by kevinlin311tw** [comment]
:laughing:
