### ISSUE TITLE
I get an error “error=cudaSuccess(2 vs. 0) out of memory？” when training. how can i adjust some configuration or image dataset？

### ISSUE THREAD

**Issue by wzvoid** [kevinlin311tw/caffe-cvprw15#30]
As to this error, is my GPU memory too small?  my GPU: GTX1050Ti  4G

At the beginning, i change both batch_size to 256 in train_prototxt file and test_prototxt file because the number of  my training image is 71460 and test image is 18465, i only change this one parameter,  that error occurs.  i don't know if the proportion of training images and test images is correct. do you have some suggestions about this? oh, the origin size of image datasets is 250*250 while cifar-10 is 32*32. but i think it does't matter because when generating leveldb, the shell will resize all images to 256*256, right?

Later, i use the same configuration as your train_prototxt, test_prototxt and solver prototxt, but the highest accuracy is only about 43% and later it reduce to 0.08 gradually... do you know what the problem is?

At last i considered if my image dataset is reasonable, i craw them from taobao, i think taobao's image quality is not high because the backgroundn of image is too complex, and it may interferer training result.
Are my guessing right?

These problems have bothered me for a long time. i wish your help ,thanks!!

**Comment by deng888529** [comment]
Did you solve this problem，I occur the same problem,I wish your help,thanks

**Comment by wzvoid** [comment]
@deng888529 
two ways:
1, your GPU memory is  relatively small，change it to (gtx1060 6G) or higher.
2, set a lower batch_size value in your prototxt. As for me, 128 is fine but 256 is not. so you  should try the  different batch_size to get specific one.
