### ISSUE TITLE
How to train a new model using my own dataset?

### ISSUE THREAD

**Issue by brisker** [kevinlin311tw/caffe-cvprw15#9]
How to train a new model using my own dataset? Thank you !

**Comment by kevinlin311tw** [comment]
Prepare your training data, and fine-tune alexnet with latent layer.

**Comment by brisker** [comment]
@kevinlin311tw   thanks, I have successfully run the code and got the model. But I am puzzled that in the "examples/cvprw15-cifar10"  there is no  mean.binaryproto  file. Could you please tell me why?  There is no need  of  mean-image-value files for your model?

**Comment by kevinlin311tw** [comment]
We use imagenet mean binaryproto file.
